hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    HaApi:
        path: /api/**
        stripPrefix: true
        serviceId: HaApi
    HaPayService:
        path: /notify/**
        stripPrefix: false
        serviceId: HaPayService